language: node_js

node_js:
 - "node"

install:
  - yarn
  - yarn add codecov

script:
  - yarn test
  - yarn build

deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_API_TOKEN"
  on:
    branch: main
    tags: true

after_success:
  - codecov