language: node_js

node_js:
 - "node"

install:
  - yarn
  - yarn add codecov

script:
  - yarn test

deploy:
  provider: npm
  edge: true # opt in to dpl v2
  on:
    branch: main
    tags: true

after_success:
  - codecov